Add release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -33,6 +33,13 @@ jobs:
       - name: Build adash platform binaries
         run: make bin
 
+      - name: Make sure tag version matches package.json
+        run: |
+          if [ $(git tag) 1= v$(cd ui && node print-version.js) ]; then
+            echo "::error file=ui/package.json::Tag does not match package.json version"
+            exit 1
+          fi
+
       - name: Create the release
         uses: "marvinpinto/action-automatic-releases@latest"
         with:
@@ -41,3 +48,12 @@ jobs:
           files: |
             bin/*
 
+      - name: Bump the package.json version number
+        run: (cd ui && npm version patch)
+
+      - name: Commit the new version number
+        - uses: EndBug/add-and-commit@v7
+          with:
+            message: 'Automatic version number bump after release'
+            pathspec_error_handling: exitAtEnd
+            pull: 'NO-PULL'
